### ISSUE TITLE
Add Link Sharing image

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaAcademy/JuliaProgrammingForNervousBeginners#2]
TODO: once this goes Public

**Comment by HenriLaurie** [comment]
Good point! The only image I have for the course specifically is unfortunately the backdrop, which won't do. Anyway, I am pretty sure you have good ones to choose from!

**Comment by logankilpatrick** [comment]
Ah, actually, this is already done. I set it up before but it didn't look like it was saving for some reason.
